# Generated by Django 2.2 on 2019-04-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='a',
            field=models.CharField(max_length=20),
        ),
    ]
