# Generated by Django 2.1.3 on 2018-11-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181113_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='items',
        ),
        migrations.AddField(
            model_name='user',
            name='items',
            field=models.ManyToManyField(to='myapp.Item'),
        ),
    ]
