# Generated by Django 2.1.3 on 2019-03-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20181113_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new',
            field=models.CharField(default='hello', max_length=10),
        ),
    ]
